# Generated by Django 5.2.1 on 2025-05-21 01:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='consultor_responsavel',
        ),
        migrations.AddField(
            model_name='holding',
            name='consultores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'consultor'}, related_name='holdings_assessoradas', to=settings.AUTH_USER_MODEL, verbose_name='Consultores Responsáveis'),
        ),
    ]
