# Generated by Django 5.2.1 on 2025-05-15 14:55

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='holding',
            old_name='valor_patrimonio_integralizado',
            new_name='bank_savings_amount',
        ),
        migrations.AddField(
            model_name='holding',
            name='company_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='company_profit_annual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='distributes_profits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holding',
            name='has_bank_savings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holding',
            name='has_companies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holding',
            name='has_heirs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holding',
            name='has_legal_issues',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holding',
            name='has_litigation_concerns',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holding',
            name='has_management_difficulties',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holding',
            name='has_multiple_assets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holding',
            name='has_paid_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holding',
            name='has_rental_properties',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holding',
            name='has_succession_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holding',
            name='heir_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='protected_assets',
            field=models.TextField(blank=True, help_text='Descrição dos bens a proteger'),
        ),
        migrations.AddField(
            model_name='holding',
            name='rental_expenses_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='rental_income_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='rental_property_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='wants_asset_protection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holding',
            name='wants_efficient_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documento',
            name='valor_referencia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor associado ao documento, se aplicável (ex: valor de um imóvel)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='processoholding',
            name='cliente_principal',
            field=models.ForeignKey(limit_choices_to={'user_type': 'cliente'}, on_delete=django.db.models.deletion.PROTECT, related_name='processos_holding', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
