# Generated by Django 5.2.1 on 2025-05-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
