# Generated by Django 5.2.1 on 2025-05-21 13:42

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_holding_consultor_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.CustomUserManager()),
            ],
        ),
    ]
