# Generated by Django 5.2.1 on 2025-05-21 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_managers_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Pasta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pastas_criadas_por_mim', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpastas', to='core.pastadocumento', verbose_name='Pasta Pai')),
                ('processo_holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas_documentos', to='core.processoholding', verbose_name='Processo da Holding')),
            ],
            options={
                'verbose_name': 'Pasta de Documento',
                'verbose_name_plural': 'Pastas de Documentos',
                'ordering': ['processo_holding', 'parent_folder__nome', 'nome'],
                'unique_together': {('processo_holding', 'parent_folder', 'nome')},
            },
        ),
    ]
