# Generated by Django 5.2.1 on 2025-05-18 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_holding_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processoholding',
            name='consultor_designado',
        ),
    ]
