# Generated by Django 5.2.1 on 2025-05-21 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pastadocumento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['processo_holding', 'pasta__nome', 'nome_documento_logico', '-versao', '-data_upload'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AddField(
            model_name='documento',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_contidos', to='core.pastadocumento', verbose_name='Pasta de Armazenamento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='processo_holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_processo', to='core.processoholding', verbose_name='Processo da Holding'),
        ),
    ]
