# Generated by Django 5.2.1 on 2025-05-18 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_processoholding_consultor_designado'),
    ]

    operations = [
    ]
