# Generated by Django 5.2.1 on 2025-05-22 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_managers'),
        ('core', '0005_alter_documento_options_documento_pasta_and_more'),
    ]

    operations = [
    ]
