# Generated by Django 5.2.1 on 2025-05-22 15:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20250521_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresult',
            name='has_investments',
            field=models.BooleanField(default=False, verbose_name='Possui Investimentos?'),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='investment_savings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Economia sobre Ganhos de Capital (Investimentos)'),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='property_state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado dos Imóveis'),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='total_investment_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Total dos Investimentos'),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='annual_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Lucro Anual (Empresas)'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='annual_rent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Renda Anual de Aluguéis'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='company_tax_regime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Regime Tributário das Empresas'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='conflict_risk',
            field=models.CharField(default='Não Aplicável', max_length=50, verbose_name='Risco de Conflito Familiar'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='has_companies',
            field=models.BooleanField(default=False, verbose_name='Possui Empresas?'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='inventory_cost_with',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Custo de Inventário (Com Holding)'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='inventory_cost_without',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Custo de Inventário (Sem Holding)'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='inventory_savings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Economia no Inventário'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='inventory_time_with',
            field=models.IntegerField(default=0, verbose_name='Tempo de Inventário com Holding (meses)'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='inventory_time_without',
            field=models.IntegerField(default=0, verbose_name='Tempo de Inventário sem Holding (meses)'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='monthly_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Lucro Mensal (Empresas)'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Renda Mensal de Aluguéis'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='number_of_companies',
            field=models.IntegerField(default=0, verbose_name='Número de Empresas'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='number_of_heirs',
            field=models.IntegerField(default=0, verbose_name='Número de Herdeiros'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='number_of_properties',
            field=models.IntegerField(default=0, verbose_name='Número de Imóveis'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='profit_savings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Economia sobre Lucros (Empresas)'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='receives_rent',
            field=models.BooleanField(default=False, verbose_name='Recebe Aluguéis?'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='rental_savings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Economia sobre Aluguéis'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='total_property_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Total dos Imóveis'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='total_savings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Economia Total Estimada'),
        ),
    ]
