# Generated by Django 5.2.1 on 2025-05-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_simulationresult_has_investments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Número de WhatsApp no formato internacional (ex: 5511999999999).', max_length=20, null=True, verbose_name='Número WhatsApp'),
        ),
    ]
